name: tests-py-pkg

on:
  push:
    branches: [ master ]
  pull_request:
    paths:
        - 'py-pkg/**'
        - '.github/workflows/tests-py-pkg.yml'
  schedule:
    # Run every Sunday
    - cron: '0 0 * * 0'

jobs:
  build:
    name: py-pkg, ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      working-directory: ./py-pkg
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Lint package
      working-directory: ./py-pkg
      run: |
        make lint

    - name: Test package
      working-directory: ./py-pkg
      run: |
        make test

    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./py-pkg/coverage.xml
        flags: py-pkg
        fail_ci_if_error: true
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == 3.8 }}
